services:
  db_local:
    image: postgres:14.2-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: dev123
      POSTGRES_USER: developer
      POSTGRES_DB: bot_data
    volumes:
      - testing_data:/var/lib/postgresql/data
volumes:
  testing_data: